# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.CharField(choices=[('Email', 'Email'), ('Text', 'Text'), ('Both', 'Both')], max_length=1),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Other', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_level',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Trained', 'Trained'), ('hasObserved', 'hasObserved'), ('beenObserved', 'beenObserved')], max_length=1),
        ),
    ]
