# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0003_auto_20160325_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
