# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import volunteers.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteer_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='volunteer',
            managers=[
                ('volunteers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.CharField(choices=[('Email', 'Email'), ('Text', 'Text'), ('Both', 'Both')], max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(choices=[('Email', 'Email'), ('Text', 'Text'), ('Both', 'Both')], max_length=50, verbose_name=volunteers.models.Contact),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_level',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Trained', 'Trained'), ('hasObserved', 'hasObserved'), ('beenObserved', 'beenObserved')], max_length=50),
        ),
    ]
