# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_contact', models.CharField(choices=[(0, 'Email'), (1, 'Text'), (2, 'Both')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_written_translate', models.BooleanField()),
                ('language_name', models.CharField(choices=[(0, 'English'), (1, 'Spanish'), (2, 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=1)),
                ('role', models.CharField(choices=[(0, 'User'), (1, 'Admin')], max_length=1)),
                ('volunteer_level', models.CharField(choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Trained'), (3, 'hasObserved'), (4, 'beenObserved')], max_length=1)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('notes', models.TextField()),
                ('inactive', models.BooleanField()),
                ('hours', models.IntegerField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Availability')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Contact')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
