# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.Volunteer'),
        ),
        migrations.AlterField(
            model_name='language',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.Volunteer'),
        ),
    ]
