# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='languages',
            field=models.ManyToManyField(to='api.Language'),
        ),
    ]
