# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160401_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
