# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160401_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_level',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Trained'), (3, 'hasObserved'), (4, 'beenObserved')], default=0),
        ),
    ]
