# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160330_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Text'), (2, 'Both')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Availability'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='languages',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='languages',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_level',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Trained'), (3, 'hasObserved'), (4, 'beenObserved')]),
        ),
    ]
