# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.IntegerField(choices=[(0, 'in-person'), (1, 'written')], default=0),
        ),
    ]
