# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160401_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
