# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
        migrations.AddField(
            model_name='assignment',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'unapproved'), (1, 'approved'), (2, 'complete')], default=0),
        ),
    ]
