# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160401_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='birthday',
        ),
    ]
