# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160405_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='carrier',
            field=models.IntegerField(choices=[(0, ''), (1, 'txt.att.net'), (2, 'messaging.sprintpcs.com'), (3, 'tmomail.net'), (4, 'vtext.com'), (5, 'sms.alltelwireless.com'), (6, 'sms.myboostmobile.com'), (7, 'cwemail.com'), (8, 'gocbw.com'), (9, 'sms.mycricket.com'), (10, 'mymetropcs.com'), (11, 'qwestmp.com'), (12, 'sms.rogers.com'), (13, 'msg.telus.com'), (14, 'email.uscc.net'), (15, 'vmobl.com')], default=0),
            preserve_default=False,
        ),
    ]
