# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160405_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignments', to='api.Volunteer'),
        ),
    ]
