# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
