# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160421_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_translation',
            field=models.BooleanField(default=False),
        ),
    ]
