# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160422_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='carrier',
            field=models.IntegerField(choices=[(0, ''), (1, 'txt.att.net'), (2, 'messaging.sprintpcs.com'), (3, 'tmomail.net'), (4, 'vtext.com'), (5, 'sms.alltelwireless.com'), (6, 'sms.myboostmobile.com'), (7, 'cwemail.com'), (8, 'gocbw.com'), (9, 'sms.mycricket.com'), (10, 'mymetropcs.com'), (11, 'qwestmp.com'), (12, 'sms.rogers.com'), (13, 'msg.telus.com'), (14, 'email.uscc.net'), (15, 'vmobl.com')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Text'), (2, 'Both')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
