# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160424_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
