# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_volunteer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_translation',
        ),
    ]
