let EnumsService = function () {
  let enums = {
    sex: {
      0: 'Male',
      1: 'Female',
      2: 'Other',
    },
    volunteer_level: {
      0: 'Unverified',
      1: 'Verified',
      2: 'Trained',
      3: 'hasObserved',
      4: 'beenObserved'
    },
    days: {
      0: 'Monday',
      1: 'Tuesday',
      2: 'Wednesday',
      3: 'Thursday',
      4: 'Friday',
      5: 'Saturday',
      6: 'Sunday',
    },
    preferred_contact: {
      0: 'Email',
      1: 'Text',
      2: 'Both',
    },
    languages: {
    	'af': 'Afrikaans',
    	'ar': 'Arabic',
    	'ast': 'Asturian',
    	'az': 'Azerbaijani',
    	'bg': 'Bulgarian',
    	'be': 'Belarusian',
    	'bn': 'Bengali',
    	'br': 'Breton',
    	'bs': 'Bosnian',
    	'ca': 'Catalan',
    	'cs': 'Czech',
    	'cy': 'Welsh',
    	'da': 'Danish',
    	'de': 'German',
    	'el': 'Greek',
    	'en': 'English',
    	'en-au': 'Australian English',
    	'en-gb': 'British English',
    	'eo': 'Esperanto',
    	'es': 'Spanish',
    	'es-ar': 'Argentinian Spanish',
    	'es-co': 'Colombian Spanish',
    	'es-mx': 'Mexican Spanish',
    	'es-ni': 'Nicaraguan Spanish',
    	'es-ve': 'Venezuelan Spanish',
    	'et': 'Estonian',
    	'eu': 'Basque',
    	'fa': 'Persian',
    	'fi': 'Finnish',
    	'fr': 'French',
    	'fy': 'Frisian',
    	'ga': 'Irish',
    	'gd': 'Scottish Gaelic',
    	'gl': 'Galician',
    	'he': 'Hebrew',
    	'hi': 'Hindi',
    	'hr': 'Croatian',
    	'hu': 'Hungarian',
    	'ia': 'Interlingua',
    	'id': 'Indonesian',
    	'io': 'Ido',
    	'is': 'Icelandic',
    	'it': 'Italian',
    	'ja': 'Japanese',
    	'ka': 'Georgian',
    	'kk': 'Kazakh',
    	'km': 'Khmer',
    	'kn': 'Kannada',
    	'ko': 'Korean',
    	'lb': 'Luxembourgish',
    	'lt': 'Lithuanian',
    	'lv': 'Latvian',
    	'mk': 'Macedonian',
    	'ml': 'Malayalam',
    	'mn': 'Mongolian',
    	'mr': 'Marathi',
    	'my': 'Burmese',
    	'nb': 'Norwegian Bokmal',
    	'ne': 'Nepali',
    	'nl': 'Dutch',
    	'nn': 'Norwegian Nynorsk',
    	'os': 'Ossetic',
    	'pa': 'Punjabi',
    	'pl': 'Polish',
    	'pt': 'Portuguese',
    	'pt-br': 'Brazilian Portuguese',
    	'ro': 'Romanian',
    	'ru': 'Russian',
    	'sk': 'Slovak',
    	'sl': 'Slovenian',
    	'sq': 'Albanian',
    	'sr': 'Serbian',
    	'sr-latn': 'Serbian Latin',
    	'sv': 'Swedish',
    	'sw': 'Swahili',
    	'ta': 'Tamil',
    	'te': 'Telugu',
    	'th': 'Thai',
    	'tr': 'Turkish',
    	'tt': 'Tatar',
    	'udm': 'Udmurt',
    	'uk': 'Ukrainian',
    	'ur': 'Urdu',
    	'vi': 'Vietnamese',
    	'zh-hans': 'Simplified Chinese',
    	'zh-hant': 'Traditional Chinese',
    },
    carriers: {
      0: "AT&T",
      1: "Sprint",
      2: "T-Mobile",
      3: "Verizon",
      4: "Alltel",
      5: "Boost",
      6: "Cellular South",
      7: "Centennial Wireless",
      8: "Cincinnati Bell",
      9: "Cricket Wireless",
      10: "Metro PCS",
      11: "Powertel",
      12: "Qwest",
      13: "Rogers",
      14: "Suncom",
      15: "Telus",
      16: "U.S. Cellular",
      17: "Virgin Mobile USA",
      18: "Other",
    },
    assignment_type: {
      0: 'in-person',
      1: 'written'
    },
    assignment_status: {
      0: 'unapproved',
      1: 'approved',
      2: 'complete'
    }
  };
  return enums;
};
export default EnumsService;
